// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/figurinhas": {
            "get": {
                "description": "Retorna todas as figurinhas cadastradas.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "figurinhas"
                ],
                "summary": "Listar figurinhas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Figurinha"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria uma nova figurinha a partir das informações enviadas no corpo da requisição.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "figurinhas"
                ],
                "summary": "Criar figurinha",
                "parameters": [
                    {
                        "description": "Dados da figurinha",
                        "name": "figurinha",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateFigurinhaRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Figurinha"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/figurinhas/{id}": {
            "get": {
                "description": "Retorna uma figurinha específica a partir do ID enviado na rota.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "figurinhas"
                ],
                "summary": "Buscar figurinha por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da figurinha",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Figurinha"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Atualiza os campos enviados de uma figurinha já cadastrada.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "figurinhas"
                ],
                "summary": "Atualizar figurinha",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da figurinha",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados para atualizar",
                        "name": "figurinha",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateFigurinhaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Figurinha"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove uma figurinha a partir do ID enviado na rota.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "figurinhas"
                ],
                "summary": "Deletar figurinha",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da figurinha",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "null",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.CreateFigurinhaRequest": {
            "type": "object",
            "required": [
                "number",
                "position",
                "type"
            ],
            "properties": {
                "number": {
                    "type": "string"
                },
                "position": {
                    "$ref": "#/definitions/domain.PosicaoJogadorFigurinha"
                },
                "type": {
                    "$ref": "#/definitions/domain.TipoFigurinha"
                }
            }
        },
        "domain.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "domain.Figurinha": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "number": {
                    "type": "string"
                },
                "position": {
                    "$ref": "#/definitions/domain.PosicaoJogadorFigurinha"
                },
                "type": {
                    "$ref": "#/definitions/domain.TipoFigurinha"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.PosicaoJogadorFigurinha": {
            "type": "string",
            "enum": [
                "goleiro",
                "zagueiro",
                "meio-campista",
                "atacante"
            ],
            "x-enum-varnames": [
                "PosicaoGoleiro",
                "PosicaoZagueiro",
                "PosicaoMeioCampo",
                "PosicaoAtacante"
            ]
        },
        "domain.TipoFigurinha": {
            "type": "string",
            "enum": [
                "comum",
                "brilhante",
                "legend_ouro",
                "legend_bronze"
            ],
            "x-enum-varnames": [
                "TipoComum",
                "TipoBrilhante",
                "TipoLegendOuro",
                "TipoLegendBronze"
            ]
        },
        "domain.UpdateFigurinhaRequest": {
            "type": "object",
            "properties": {
                "number": {
                    "type": "string"
                },
                "position": {
                    "$ref": "#/definitions/domain.PosicaoJogadorFigurinha"
                },
                "type": {
                    "$ref": "#/definitions/domain.TipoFigurinha"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API de Figurinhas",
	Description:      "API simples para gerenciar figurinhas.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
